# Sample .travis.yml

language: c

os:
  - osx

before_install:
  - 

install: true

script:
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew install gcc
  - brew install open-mpi
  - mpiexec --version
  - mpiexec --showme:incdirs
  - mpiexec --showme:libdirs
  - mpiexec -np 2 hostname

notifications:
  email:
    on_success: no
    on_failure: no

sudo: required
